name: CI

on: [push]

jobs:
  check:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Checkout Latest
      - name: Checkout Latest
        uses: actions/checkout@v6
        with:
          submodules: 'true'
          ssh-key: '${{ secrets.SUB_SSH_KEY }}'

      # Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Make Gradle Wrapper Executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew
          
      # Setup Cache
      - name: Setup Gradle Cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      # Check the code with Android linter + kotlinter
      - name: Run Android Linter + kotlinter
        run: ./gradlew check

      # Populate Secrets
      - name: Decode secrets.xml
        env:
          SECRETS: ${{ secrets.SECRETS }}
        run: echo $SECRETS > ./app/src/main/res/values/secrets.xml
  
      # Run unit tests
      - name: Run Unit Tests
        run: ./gradlew test

      # Assemble debug apk to send to firebase test lab
      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

      # Assemble debug test apk to send to firebase test lab
      - name: Assemble Debug Test APK
        run: ./gradlew assembleDebugAndroidTest

      # Run instrumented tests on firebase test lab
      # Deprecated: just run these manually
      #- name: Run tests on Firebase Test Lab
      #  uses: asadmansr/Firebase-Test-Lab-Action@v1.0
      #  with:
      #    arg-spec: '.github/tests.yml:android-pixel-4'
      #  env:
      #    SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
